import { Subject } from './types';

export const TOPICS: Record<Subject, string[]> = {
  Physics: [
    'Current Electricity',
    'Ray Optics',
    'Modern Physics',
    'Electromagnetic Induction',
    'Alternating Current',
    'Dual Nature of Matter',
    'Atoms and Nuclei',
    'Semiconductors',
    'Laws of Motion',
    'Work, Energy and Power',
    'Gravitation',
    'Thermodynamics',
    'Kinetic Theory of Gases',
    'Waves',
    'Electrostatics',
    'Capacitors',
    'Magnetic Effects of Current',
    'Magnetism',
    'Communication Systems',
    'Units and Measurements',
  ],
  Chemistry: [
    'Chemical Bonding',
    'Organic Reactions',
    'Electrochemistry',
    'Chemical Kinetics',
    'Coordination Compounds',
    'P-Block Elements',
    'd and f Block Elements',
    'Aldehydes and Ketones',
    'Carboxylic Acids',
    'Amines',
    'Biomolecules',
    'Polymers',
    'Solutions',
    'Solid State',
    'Surface Chemistry',
    'Equilibrium',
    'Thermodynamics (Chemistry)',
    'Haloalkanes and Haloarenes',
    'Alcohols, Phenols and Ethers',
    'Hydrocarbons',
  ],
  Biology: [
    'Human Physiology',
    'Genetics',
    'Plant Physiology',
    'Reproduction',
    'Cell Biology',
    'Ecology',
    'Evolution',
    'Biotechnology',
    'Animal Kingdom',
    'Plant Kingdom',
    'Molecular Basis of Inheritance',
    'Principles of Inheritance',
    'Human Health and Disease',
    'Microbes in Human Welfare',
    'Environmental Issues',
    'Biodiversity and Conservation',
    'Digestion and Absorption',
    'Breathing and Exchange of Gases',
    'Body Fluids and Circulation',
    'Excretory Products and Elimination',
  ],
};

export const SUBJECT_COLORS: Record<Subject, { bg: string; text: string; border: string; light: string }> = {
  Physics: {
    bg: 'bg-blue-600',
    text: 'text-blue-600',
    border: 'border-blue-600',
    light: 'bg-blue-50',
  },
  Chemistry: {
    bg: 'bg-emerald-600',
    text: 'text-emerald-600',
    border: 'border-emerald-600',
    light: 'bg-emerald-50',
  },
  Biology: {
    bg: 'bg-violet-600',
    text: 'text-violet-600',
    border: 'border-violet-600',
    light: 'bg-violet-50',
  },
};

export const SUBJECT_ICONS: Record<Subject, string> = {
  Physics: '⚡',
  Chemistry: '🧪',
  Biology: '🧬',
};
